AM.UI.Web/Controllers/FlightController.cs
using AM.ApplicationCore.Domain;
using AM.ApplicationCore.Interfaces;
using AM.ApplicationCore.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AM.UI.Web.Controllers
{
    public class FlightController : Controller
    {

        IFlightService sf;
        IServicePlanes sp;

        public FlightController(IFlightService sf, IServicePlanes sp)
        {
            this.sf = sf;
            this.sp = sp;
        }

        // GET: FlightController
        public ActionResult Index(DateTime? dateDepart)
        {
            if (dateDepart == null)
                return View(sf.GetAll().ToList());
            else
                return View(sf.GetMany(f => f.FlightDate.Date.Equals(dateDepart.Value.Date)).ToList());
        }

        public ActionResult Sort()

        {

            return View("Index", sf.SortFlights());

        }



        // GET: FlightController/Details/5
        public ActionResult Details(int id)
        {
            // Retrieve the flight using the service method
            var flight = sf.GetById(id);

            // Check if the flight was found
            if (flight == null)
            {
                return NotFound(); // Return 404 if the flight is not found
            }

            // Return the View with the flight details
            return View(flight);
        }


        // GET: FlightController/Create
        public ActionResult Create()
        {
            ViewBag.planeList = new SelectList(sp.GetAll(), "PlaneId", "Capacity");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Flight f, IFormFile PilotImage)
        {
            try
            {
                if (PilotImage != null && PilotImage.ContentType.StartsWith("image"))
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", PilotImage.FileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        PilotImage.CopyTo(stream);
                    }

                    f.Pilot = PilotImage.FileName;
                }

                sf.Add(f);
                sf.Commit();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // GET: FlightController/Edit/5
        public ActionResult Edit(int id)
        {
            var flight = sf.GetById(id);
            if (flight == null)
            {
                return NotFound();
            }
            ViewBag.planeList = new SelectList(sp.GetAll(), "PlaneId", "Capacity");
            return View(flight);
        }

        // POST: FlightController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Flight flight, IFormFile PilotImage)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Handle Pilot Image if uploaded
                    if (PilotImage != null && PilotImage.ContentType.StartsWith("image"))
                    {
                        var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", PilotImage.FileName);

                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            PilotImage.CopyTo(stream);
                        }

                        flight.Pilot = PilotImage.FileName;  // Update pilot image name
                    }

                    // If the flight is found and updated, commit the changes
                    sf.Update(flight);
                    sf.Commit();

                    return RedirectToAction(nameof(Index));
                }

                // If model state is invalid, reload plane list
                ViewBag.planeList = new SelectList(sp.GetAll(), "PlaneId", "Capacity");
                return View(flight);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Error updating flight: " + ex.Message);
                ViewBag.planeList = new SelectList(sp.GetAll(), "PlaneId", "Capacity");
                return View(flight);
            }
        }

        // GET: FlightController/PlaneDetails/5
        public ActionResult PlaneDetails(int id)
        {
            // Récupérer le détail de l'avion basé sur l'ID
            var plane = sp.GetById(id);
            if (plane == null)
            {
                return NotFound(); // Retourner 404 si l'avion n'est pas trouvé
            }
            return View(plane); // Afficher la vue avec les détails de l'avion
        }



        // GET: FlightController/Delete/5
        public ActionResult Delete(int id)
        {
            var flight = sf.GetById(id);  // Retrieve the flight by id
            if (flight == null)
            {
                return NotFound();  // Return 404 if flight is not found
            }
            return View(flight);  // Display confirmation view
        }

        // POST: FlightController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var flight = sf.GetById(id);  // Retrieve the flight by id
                if (flight == null)
                {
                    return NotFound();  // Return 404 if flight not found
                }

                // Delete the flight
                sf.Delete(flight);
                sf.Commit();  // Apply changes to the database

                return RedirectToAction(nameof(Index));  // Redirect to index after deletion
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Error deleting flight: " + ex.Message);
                return View();  // Return to Delete confirmation view if error occurs
            }
        }
    }


    }

AM.UI.Web/Views/Flight/Create.cshtml
@model AM.ApplicationCore.Domain.Flight

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Departure" class="control-label"></label>
                <input asp-for="Departure" class="form-control" />
                <span asp-validation-for="Departure" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pilot" class="control-label"></label>
                <input type="file" name="PilotImage" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffectiveArrival" class="control-label"></label>
                <input asp-for="EffectiveArrival" class="form-control" />
                <span asp-validation-for="EffectiveArrival" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedDuration" class="control-label"></label>
                <input asp-for="EstimatedDuration" class="form-control" />
                <span asp-validation-for="EstimatedDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightDate" class="control-label"></label>
                <input asp-for="FlightDate" class="form-control" />
                <span asp-validation-for="FlightDate" class="text-danger"></span>
            </div>
           @*  <div class="form-group">
                <label asp-for="FlightId" class="control-label"></label>
                <input asp-for="FlightId" class="form-control" />
                <span asp-validation-for="FlightId" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="PlaneFK" class="control-label"></label>
@*                 <input asp-for="PlaneFK" class="form-control" />
                
 *@
                <select asp-for="PlaneFK" class="form-control" 
                asp-items="ViewBag.planeList"></select>
 <span asp-validation-for="PlaneFK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartureDate" class="control-label"></label>
                <input asp-for="DepartureDate" class="form-control" />
                <span asp-validation-for="DepartureDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.Web/Views/Flight/Delete.cshtml
@model AM.ApplicationCore.Domain.Flight

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departure)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departure)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pilot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pilot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EffectiveArrival)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EffectiveArrival)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedDuration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedDuration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneFK)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneFK)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartureDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartureDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AM.UI.Web/Views/Flight/Details.cshtml
@model AM.ApplicationCore.Domain.Flight

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departure)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departure)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pilot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pilot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EffectiveArrival)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EffectiveArrival)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedDuration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedDuration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneFK)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneFK)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartureDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartureDate)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

AM.UI.Web/Views/Flight/Edit.cshtml
@model AM.ApplicationCore.Domain.Flight

@{
    ViewData["Title"] = "Edit";
}



<h4>Edit Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <!-- Flight Fields -->
            <div class="form-group">
                <label asp-for="Departure" class="control-label"></label>
                <input asp-for="Departure" class="form-control" />
                <span asp-validation-for="Departure" class="text-danger"></span>
            </div>

            <!-- Pilot Image Field -->
            <div class="form-group">
                <label for="PilotImage" class="control-label">Pilot Image</label>
                <input type="file" name="PilotImage" class="form-control" />
            </div>

            <!-- Plane Dropdown -->
            <div class="form-group">
                <label asp-for="PlaneFK" class="control-label"></label>
                <select asp-for="PlaneFK" class="form-control" asp-items="ViewBag.planeList"></select>
                <span asp-validation-for="PlaneFK" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.Web/Views/Flight/Index.cshtml
@model IEnumerable<AM.ApplicationCore.Domain.Flight>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<form asp-action="Index">
    <fieldset>
        <legend>Recherche</legend>
        Saisir une date de départ :
        <input type="date" name="dateDepart" />
        <input type="submit" value="Search" />
    </fieldset>
</form>
<form asp-action="Sort">

    <fieldset>

        <input type="submit" value="Sort" />

    </fieldset>

</form>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Departure)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EffectiveArrival)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstimatedDuration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaneFK)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartureDate)
            </th>
            <th>@Html.DisplayNameFor(model => model.Pilot)</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
              <partial name="_FlightDetails" model="item">        
              </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departure)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EffectiveArrival)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstimatedDuration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlightDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlightId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlaneFK)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartureDate)
            </td>
            <td>
                <img src="~/uploads/@item.Pilot" width="50" height="50"/>
            </td>
            <td>
                    @Html.ActionLink("PlaneDetails", "PlaneDetails", "Flight", new { id = item.PlaneFK }) | <!-- Ajoutez le lien vers les détails de l'avion -->
                    @Html.ActionLink("Edit", "Edit", new { id = item.FlightId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.FlightId }) | 
                    @Html.ActionLink("Delete", "Delete", new { id = item.FlightId }) 
            </td>
        </tr>
}
    </tbody>
</table>

AM.UI.Web/Views/Flight/PlaneDetails.cshtml
@model AM.ApplicationCore.Domain.Plane

@{
    ViewData["Title"] = "PlaneDetails";
}

<h1>PlaneDetails</h1>

<div>
    <h4>Plane</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AirLineLogo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AirLineLogo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufactureDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufactureDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneType)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

AM.UI.Web/Views/Flight/_FlightDetails.cshtml
@model AM.ApplicationCore.Domain.Flight

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div>
    <dl>nombre de passagers</dl>
    <dl>@Model.Passengers.Count()</dl>
    <dl>Capacity avion</dl>
    <dl>@Model.Plane.Capacity.</dl>
    <dl>type avion</dl>
    <dl>@Model.Plane.PlaneType</dl>
    
</div>